var str=`'Ashley','Professor'
'Samantha','Actor'
'Julia','Doctor'
'Britney','Professor'
'Maria','Professor'
'Meera','Professor'
'Priya','Doctor'
'Priyanka','Professor'
'Jennifer','Actor'
'Ketty','Actor'
'Belvet','Professor'
'Naomi','Professor'
'Jane','Singer'
'Jenny','Singer'
'Kristeen','Singer'
'Christeen','Singer'
'Eve','Actor'
'Aamina','Doctor'`;
var x= str.split("\n").map((e)=>"("+e+"),").join("\n")
console.log(x)